server:
  port: 8085

spring:
  application:
    name: hf-donation-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-donation:5432/donationdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

# Zipkin Configuration for Docker
management.zipkin.tracing.endpoint: ${ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans

logging:
  level:
    com.careforall.donation: INFO
    org.hibernate.SQL: INFO
    org.springframework.scheduling: INFO
